# Generated by Django 4.2 on 2024-10-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_product_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('cloth_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('cloth_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_id', models.IntegerField()),
                ('mask_type', models.CharField(max_length=100)),
                ('mask_image', models.CharField(max_length=255)),
                ('cloth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.cloth')),
            ],
            options={
                'unique_together': {('cloth_id', 'mask_id')},
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
