# Generated by Django 4.2 on 2024-10-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_cloth_mask_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mask',
            old_name='cloth_id',
            new_name='cloth',
        ),
        migrations.AlterUniqueTogether(
            name='mask',
            unique_together={('cloth', 'mask_id')},
        ),
    ]
