# Generated by Django 4.2 on 2024-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_cloth_accessories_alter_cloth_body_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=100)),
                ('user_description', models.TextField()),
                ('upload_time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='user_upload/')),
            ],
        ),
    ]
