# Generated by Django 4.2 on 2024-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_userupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
