# Generated by Django 4.2 on 2024-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_userupload_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='image',
        ),
        migrations.AddField(
            model_name='userupload',
            name='user_image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
