# Generated by Django 4.2 on 2024-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
