# Generated by Django 4.2 on 2024-10-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_memory_delete_userupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='upload_time',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='memory',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
