# Generated by Django 4.2 on 2024-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_rename_upload_time_memory_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='transaction',
            field=models.CharField(default='user upload', max_length=255),
        ),
    ]
